# gem pg

development:
  adapter: postgresql
  encoding: unicode
  database: grocery_book_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: grocery_book_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: grocery_book_production
  pool: 5
